# Generated by Django 5.2.12 on 2026-03-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addresses",
            old_name="full_name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="addresses",
            name="last_name",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
