# Generated by Django 5.2.12 on 2026-03-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_full_name_addresses_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresses",
            name="type",
            field=models.CharField(
                choices=[("home", "Home"), ("work", "Work"), ("other", "Other")],
                default="home",
                max_length=10,
            ),
        ),
    ]
