# Generated by Django 5.2.13 on 2026-04-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReturnRequest",
        ),
    ]
