# Generated by Django 5.2.12 on 2026-04-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="color_hex",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
