# Generated by Django 5.2.12 on 2026-04-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_variant_color_hex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="color_hex",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
