# Generated by Django 5.2.12 on 2026-03-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_variantimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
