# Generated by Django 5.2.12 on 2026-04-07 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_variant_color_hex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="stock",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
    ]
