# Generated by Django 5.2.13 on 2026-04-27 04:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_variantimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
