# Generated by Django 5.2.13 on 2026-04-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_variantimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantimage",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
