# Generated by Django 5.2.12 on 2026-03-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                default="profile_pic/default.jpg", upload_to="profile_pic/"
            ),
        ),
    ]
