# Generated by Django 5.2.12 on 2026-03-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                default="profile_photos/default.jpg", upload_to="profile_pic/"
            ),
        ),
    ]
