# Generated by Django 5.2.12 on 2026-03-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="update_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
