# Generated by Django 5.2.12 on 2026-03-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_phone_number_alter_user_update_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
