# Generated by Django 5.2.13 on 2026-04-24 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_referral_code_referralrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralrecord",
            name="reward_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
