# Generated by Django 5.2.13 on 2026-04-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_referralrecord_reward_paid_user_referred_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="profile_photos/default.jpg",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
    ]
