# Generated by Django 5.2.13 on 2026-04-27 04:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="profile_photos/default.jpg",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
