# Generated by Django 5.2.13 on 2026-04-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_returnrequest_is_eligible_order_cancelled_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returnrequest",
            name="status",
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("INITIATED", "Initiated"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
    ]
