# Generated by Django 5.2.13 on 2026-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_order_cancellation_reason_order_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="orderstatushistory",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="returnrequest",
            name="admin_notes",
        ),
        migrations.RemoveField(
            model_name="returnrequest",
            name="refund_status",
        ),
        migrations.RemoveField(
            model_name="returnrequest",
            name="return_status",
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Return Requested"),
                    ("APPROVED", "Return Approved"),
                    ("REJECTED", "Return Rejected"),
                    ("CANCELLED", "Return Cancelled"),
                    ("PICKUP_COMPLETED", "Pickup Completed"),
                    ("REFUND_INITIATED", "Refund Initiated"),
                    ("REFUNDED", "Refund Completed"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED", "Returned"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED", "Returned"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
