# Generated by Django 5.2.13 on 2026-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_order_cancellation_reason_remove_order_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="returnrequest",
            old_name="cancelled_at",
            new_name="returned_at",
        ),
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED", "Returned"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="admin_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="return_requests/"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("REFUND_IN_PROGRESS", "Refund in Progress"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURN_APPROVED", "Return Approved"),
                    ("RETURN_REJECTED", "Return Rejected"),
                    ("RETURNED", "Returned"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURN_APPROVED", "Return Approved"),
                    ("RETURN_REJECTED", "Return Rejected"),
                    ("RETURNED", "Returned"),
                    ("REFUND_INITIATED", "Refund Initiated"),
                    ("REFUNDED", "Refunded"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PICKED_UP", "Picked Up"),
                    ("RETURNED", "Returned"),
                    ("REFUND_IN_PROGRESS", "Refund in Progress"),
                    ("REFUNDED", "Refunded"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
    ]
