# Generated by Django 5.2.13 on 2026-04-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_returned_at_returnrequest_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="courier_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="admin_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="refund_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORIGINAL_SOURCE", "Original Payment Source"),
                    ("WALLET", "Account Wallet"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("N/A", "Not Applicable"),
                    ("PENDING", "Pending"),
                    ("INITIATED", "Initiated"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="N/A",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURN_APPROVED", "Return Approved"),
                    ("RETURN_PICKED_UP", "Return Picked Up"),
                    ("RETURN_RECEIVED", "Return Received"),
                    ("REFUND_INITIATED", "Refund Initiated"),
                    ("REFUND_COMPLETED", "Refund Completed"),
                    ("RETURN_COMPLETED", "Return Completed"),
                    ("RETURN_REJECTED", "Return Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURN_APPROVED", "Return Approved"),
                    ("RETURN_PICKED_UP", "Return Picked Up"),
                    ("RETURN_RECEIVED", "Return Received"),
                    ("REFUND_INITIATED", "Refund Initiated"),
                    ("REFUND_COMPLETED", "Refund Completed"),
                    ("RETURN_COMPLETED", "Return Completed"),
                    ("RETURN_REJECTED", "Return Rejected"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Return Requested"),
                    ("APPROVED", "Return Approved"),
                    ("PICKED_UP", "Return Picked Up"),
                    ("RECEIVED", "Return Received"),
                    ("REFUND_INITIATED", "Refund Initiated"),
                    ("REFUND_COMPLETED", "Refund Completed"),
                    ("COMPLETED", "Return Completed"),
                    ("REJECTED", "Return Rejected"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
    ]
