# Generated by Django 5.2.13 on 2026-04-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_orderitem_item_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURN_APPROVED", "Return Approved"),
                    ("RETURN_PICKUP_SCHEDULED", "Return Pickup Scheduled"),
                    ("RETURN_PICKED_UP", "Return Picked Up"),
                    ("RETURN_REJECTED", "Return Rejected"),
                ],
                max_length=50,
            ),
        ),
    ]
