# Generated by Django 5.2.13 on 2026-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_order_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURN_APPROVED", "Return Approved"),
                    ("RETURN_PICKUP_SCHEDULED", "Return Pickup Scheduled"),
                    ("RETURN_PICKED_UP", "Return Picked Up"),
                    ("RETURN_RECEIVED", "Return Received"),
                    ("RETURN_INSPECTED", "Return Inspected"),
                    ("RETURN_REFUND_INITIATED", "Return Refund Initiated"),
                    ("RETURN_REFUNDED", "Return Refunded"),
                    ("RETURN_REJECTED", "Return Rejected"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURN_APPROVED", "Return Approved"),
                    ("RETURN_PICKUP_SCHEDULED", "Return Pickup Scheduled"),
                    ("RETURN_PICKED_UP", "Return Picked Up"),
                    ("RETURN_RECEIVED", "Return Received"),
                    ("RETURN_INSPECTED", "Return Inspected"),
                    ("RETURN_REFUND_INITIATED", "Return Refund Initiated"),
                    ("RETURN_REFUNDED", "Return Refunded"),
                    ("RETURN_REJECTED", "Return Rejected"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Return Requested"),
                    ("APPROVED", "Return Approved"),
                    ("PICKUP_SCHEDULED", "Return Pickup Scheduled"),
                    ("PICKED_UP", "Return Picked Up"),
                    ("REJECTED", "Return Rejected"),
                    ("RECEIVED", "Return Received"),
                    ("INSPECTED", "Return Inspected"),
                    ("REFUND_INITIATED", "Return Refund Initiated"),
                    ("REFUNDED", "Return Refunded"),
                ],
                default="REQUESTED",
                max_length=50,
            ),
        ),
    ]
