# Generated by Django 5.2.13 on 2026-04-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_orderitem_item_status_and_more"),
        ("coupon", "0002_couponusage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="coupon.coupon",
            ),
        ),
        migrations.DeleteModel(
            name="Coupon",
        ),
    ]
