# Generated by Django 5.2.13 on 2026-04-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_order_coupon_delete_coupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price after applying proportional discount",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Original price at the time of purchase",
                max_digits=10,
            ),
            preserve_default=False,
        ),
    ]
