# Generated by Django 5.2.13 on 2026-04-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_orderitem_price_orderitem_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Final unit price at purchase time",
                max_digits=10,
            ),
        ),
    ]
