# Generated by Django 5.2.13 on 2026-04-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_orderitem_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returnrequest",
            name="admin_remarks",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Direct purchase price (synced with final_price)",
                max_digits=10,
            ),
        ),
    ]
