# Generated by Django 5.2.13 on 2026-04-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_banner_image_alter_homepagevideo_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(upload_to="banners/"),
        ),
        migrations.AlterField(
            model_name="homepagevideo",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="homepage_videos/"),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="returns/"),
        ),
    ]
