# Generated by Django 5.2.13 on 2026-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_banner_image_alter_homepagevideo_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("PARTIAL_CANCELLED", "Partial Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("PARTIAL_CANCELLED", "Partial Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURN_APPROVED", "Return Approved"),
                    ("RETURN_PICKUP_SCHEDULED", "Return Pickup Scheduled"),
                    ("RETURN_PICKED_UP", "Return Picked Up"),
                    ("RETURN_RECEIVED", "Return Received"),
                    ("RETURN_INSPECTED", "Return Inspected"),
                    ("RETURN_REFUND_INITIATED", "Return Refund Initiated"),
                    ("RETURN_REFUNDED", "Return Refunded"),
                    ("RETURN_REJECTED", "Return Rejected"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
