# Generated by Django 5.2.13 on 2026-04-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                    ("VOIDED", "Voided"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
