# Generated by Django 5.2.13 on 2026-05-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="net_paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Actual final paid amount for this line (base + tax - coupon)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Proportional tax amount for this item line",
                max_digits=10,
            ),
        ),
    ]
