# Generated by Django 5.2.13 on 2026-05-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_orderitem_net_paid_amount_orderitem_tax_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="offer_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Product/Category offer discount for this line",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Coupon discount share for this line",
                max_digits=10,
            ),
        ),
    ]
