# Generated by Django 5.2.13 on 2026-05-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_orderitem_offer_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Direct purchase price (after product offers)', max_digits=10),
        ),
    ]
