# Generated by Django 5.2.13 on 2026-04-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")],
                default="CREDIT",
                max_length=20,
            ),
        ),
    ]
